file:
  directory: D:/2024-02/download/tdd

spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3_test
    username: root
    password: green502
  sql:
    init:
      mode: always